site_name: RLCMS Documentation
nav:
  - Home: index.md
  - About: about.md
  - Command Line Tools: cli.md
  - Colab Notebooks:
    - compositing: colab\compositing.md
    - primitives: colab\primitives.md
    - sampling: colab\sampling.md
  - API Reference:
    - composites module: composites.md
    - covariates module: covariates.md
    - harmonics module: harmonics.md
    - primitives module: primitives.md
    - sampling module: sampling.md
    - utils module: utils.md

theme:
  name: material
  favicon: img/rlcms_logo_darkblue_fill.png # thumbnail of broswer tab
  logo: img/rlcms_logo.png # what appears in header of site
  palette:
    primary: custom
  features: 
    - navigation.footer

extra_css:
  - stylesheets/extra.css

plugins:
- search
- mkdocstrings:
    enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
    custom_templates: templates
    default_handler: python
    handlers:
      python:
        options:
          show_source: false

repo_url: https://github.com/sig-gis/rlcms
repo_name: sig-gis/rlcms

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/sig-gis/rlcms
  # pypi 
  # social: 
  #   - icon: fontawesome/brands/pypi
  #     link: https://pypi.org/project/rlcms/
